ruby '2.2.3'
source 'https://rubygems.org'

gem 'active_link_to'
gem 'activeresource'
gem 'airbrake'
gem 'asset_sync'
gem 'better_errors', group: :development
gem 'binding_of_caller', group: :development
gem 'braintree'
gem 'browser_details', git: 'git://github.com/niedfelj/browser_details.git', branch:'master'
gem 'byebug', group: :development
gem 'capybara', group: [:development, :test]
gem 'clear_cms', git: 'git://github.com/ilanaseid/clear_cms.git', branch:'rails4_bootstrap3'
gem 'clockwork'
gem 'codeclimate-test-reporter', group: :test
gem 'coffee-rails'
gem 'compass-rails'
gem 'compass-core',  git: 'https://github.com/Davidiusdadi/compass.git',  branch: 'core'
gem 'config'
gem 'database_cleaner', group: [:development, :test]
gem 'factory_girl_rails'
gem 'ffaker'
gem 'fog-aliyun'
gem 'foreman', group: [:development, :test]

gem 'gibbon', '~>1.0'
gem 'jquery-rails'
gem 'kaminari-bootstrap', '~> 0.1.3'
gem 'launchy', group: [:development, :test]
gem 'mail', '2.5.4'
gem 'markitup-rails', git: 'git://github.com/niedfelj/markitup-rails.git', branch:'master'
gem 'money'
gem 'mongoid', git: 'git://github.com/niedfelj/mongoid.git', branch:'all_patches'
gem 'mongoid-history', git: 'git://github.com/niedfelj/mongoid-history.git', branch:'versionless'
gem 'moped', git: 'git://github.com/niedfelj/moped.git', branch:'all_patches'
gem 'net-sftp'
gem 'newrelic-carrierwave', git: 'git://github.com/niedfelj/newrelic-carrierwave.git', branch:'mini_magick_fixes'
gem 'newrelic-excon'
gem 'newrelic-moped'
gem 'newrelic-redis'
gem 'newrelic_rpm'
gem 'non-stupid-digest-assets'
gem 'numbers_and_words'
gem 'pg'
gem 'pry-rails'
gem 'puma'
gem 'quiet_assets'
gem 'formtastic', git: 'git://github.com/justinfrench/formtastic.git', branch:'2.3-stable'
gem 'rack-rewrite'
gem 'rack-ssl-enforcer'
gem 'rails', '4.2.4'
gem 'rails_12factor'
gem 'rails_stdout_logging', git: 'git://github.com/niedfelj/rails_stdout_logging.git', branch:'master'
gem 'redis-rails'
gem 'redis-store'
gem 'request_store'
gem 'rspec-rails', group: [:development, :test]
gem 'ruby-trello'
gem 'sass', '>= 3.3.0'
gem 'sass-rails'
gem 'selenium-webdriver', '~> 2.45.0', group: [:development, :test]
gem 'sidekiq', '< 4.0'
gem 'sidekiq-failures'
gem 'sidekiq-throttler'
gem 'sinatra', require: nil
gem 'solidus'
gem 'solidus_auth_devise'
#gem 'spree', github: 'assembledbrands/spree', branch: '3-0-stable'
#gem 'spree_auth_devise', github: 'assembledbrands/spree_auth_devise', branch: '3-0-stable', ref: 'f652a0d796a36c8ff2e5240f1f01bf4c9bd43b8b'
#gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'sunspot_rails'
gem 'sunspot_solr'
gem 'tagmanager-rails', '3.0.0.1'
gem 'transpec'
gem 'twitter-bootstrap-rails', '2.2.8'
gem 'uglifier'
