#!/bin/bash

if [ $1=='start' ] 
  then
  
  echo 'Starting services...'

  #postgres setup
  ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
  
  
  #mongo setup
  ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
  
  
  #redis setup
  ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
  
  
  #setup a separate instance of solr for test
  RAILS_ENV=test bundle exec rake sunspot:solr:run

fi

if [ $1=='stop' ] 
  then
  echo 'Stopping services...'
fi
