# Testing UA for GA, see production for actual
google_analytics_ua: UA-39620740-4
facebook_app_id: some_id
canonical_url_root: https://www.elanstudio.com
mailassets_url_root: https://www.elanstudio.com

social_media:
  twitter_url: https://twitter.com/elanstudiony
  twitter_username: elanstudiony
  facebook_url: https://www.facebook.com/elanstudionyc
  tumblr_url: http://elanstudionyc.tumblr.com
  instagram_url: https://instagram.com/elan_studio
  instagram_username: elan_studio
  pinterest_url: https://www.pinterest.com/elan_studio/

contact_info:
  service_email: help@elanstudio.com
  service_phone: + 1 212 472 1096
  orderinq_email: orders@elanstudio.com
  jobs_email: careers@elanstudio.com
  press_email: media@elanstudio.com
  merchandising_email: merchandising@elanstudio.com
  operations_email: operations@elanstudio.com
  apartment_visits_email: appointments_tribeca@elanstudio.com

# Sandbox, see production settings for ENV...this is now set directly in the spree.rb initializer
braintree:
  use_production_gateway: <%= ENV['BRAINTREE_USE_PRODUCTION_GATEWAY'] || false %>
  name: Braintree Sandbox
  environment: sandbox
  merchant_id: x8qs3hnwp2gvqcs7
  public_key: 4cwkj9bjrgf9crw8
  private_key: 9577074424f696d7bf38b0347c183eb9
  client_side_encryption_key: MIIBCgKCAQEA60/whTi2sweWAAnjKnMAf7BlrdqqDAq2GcdpNr02YiFV3GvR6DpN4XuwDJ5MvDlGO3zszhwE/F0eitsPE7wfFAKQ0hHjx4/RUGYGSgoBnd3JLYuJ8yBAARNcxErlrisxLDewEGjm3s+oo6ofgIYeBZa1JWt+COhT4FlXaXvJ6sccOI0Bauqkit8dKbPXVyTHpjBpvgL8lSyLF4pV6qwowRK4Bo3w1JDFY6RwMl29j1sXKDJoLMRneBMAFkhlnm+kl6zSx6/cZ0B52EBlXtT++lwlNsZio9emXGzDPC0QfSJp1DND/FwePzwTGp0js963ZcnMfKz+7JHceyrXNz75cwIDAQAB

order_mailer_bcc: retailops@elanstudio.com
order_mailer_cc: order_cc@elanstudio.com
order_mailer_from: Elan Studio <orders@elanstudio.com>

brightpearl:
  readonly: <%= ENV['BRIGHTPEARL_READONLY'] || true %>
  disable_sync: <%= ENV['BRIGHTPEARL_DISABLE_SYNC'] || false %>

mailchimp:
  readonly: <%= ENV['MAILCHIMP_READONLY'] || true %>
  environment: <%= ENV['MAILCHIMP_ENVIRONMENT'] || 'sandbox' %>
  api_key: <%= ENV['MAILCHIMP_API_KEY'] || '7ba2a6a3b61bc37c7d170714966c0d24-us11' %> # Sandbox account

pagination:
  per_page_less: 36
  per_page_more: 108

trigger_emails:
  disable_product_notification_emails: <%= ENV['DISABLE_PRODUCT_NOTIFICATION_EMAILS'] || true %>

# spree:
#   site_name: <%= ENV['SPREE_SITE_NAME'] || 'The Line' %>
