google_analytics_ua: 'tbd'
google_analytics_affiliation: Elan Studio Development
google_analytics_domain: '0.0.0.0'
heap_analytics_display: false
heap_analytics_id: 'tbd'
shareasale_affiliate_display: false
brickwork_pixel_display: false
hivewyre_analytics_display: false
optimizely_enabled: false
optimizely_project_id: 'tbd'
webfonts_enabled: true
usersnap_api_key: 'tbd'
chartbeat_enabled: false
steelhouse_enabled: false
effective_spend_ftp:
  host: 'uploads.google.com'
  username: 'tbd'
effective_spend_analytics_display: false
