google_analytics_ua: <%= ENV['GOOGLE_ANALYTICS_UA'] || false %>
google_analytics_affiliation: <%= ENV['GOOGLE_ANALYTICS_AFFILIATION'] || 'Elan Studio' %>
google_analytics_domain: <%= ENV['GOOGLE_ANALYTICS_DOMAIN'] || 'elanstudio.com' %>
heap_analytics_display: <%= ENV['HEAP_ANALYTICS_DISPLAY'] || true %>
heap_analytics_id: <%= ENV['HEAP_ANALYTICS_ID'] || false %>
shareasale_affiliate_display: <%= ENV['SHAREASALE_AFFILIATE_DISPLAY'] || true %>
brickwork_pixel_display: <%= ENV['BRICKWORK_PIXEL_ENABLED'] || false %>
hivewyre_analytics_display: <%= ENV['HIVEWYRE_ANALYTICS_DISPLAY'] || true %>
canonical_url_root: https://www.elanstudio.com
mailassets_url_root: https://www.elanstudio.com
optimizely_enabled: <%= ENV['OPTIMIZELY_ENABLED'] || false %>
webfonts_enabled: <%= ENV['WEBFONTS_ENABLED'] || true %>
usersnap_api_key: <%= ENV['USERSNAP_API_KEY']  %>
chartbeat_enabled: <%= ENV['CHARTBEAT_ENABLED'] || false %>
steelhouse_enabled: <%= ENV['STEELHOUSE_ENABLED'] || true %>

brightpearl:
  readonly: <%= ENV['BRIGHTPEARL_READONLY'] || false %>

mailchimp:
  readonly: <%= ENV['MAILCHIMP_READONLY'] || false %>

effective_spend_analytics_display: <%= ENV['EFFECTIVE_SPEND_ANALYTICS_DISPLAY'] || true %>
effective_spend_ftp:
  host: <%= ENV['EFFECTIVE_SPEND_HOST'] || 'uploads.google.com' %>
  username: <%= ENV['EFFECTIVE_SPEND_USERNAME'] %>
  password: <%= ENV['EFFECTIVE_SPEND_PASSWORD'] %>
