google_analytics_ua: UA-39620740-4
google_analytics_affiliation: The Line Testing
google_analytics_domain: 'staging.theline.com'
shareasale_affiliate_display: false
brickwork_pixel_display: false
hivewyre_analytics_display: false
heap_analytics_display: false
heap_analytics_id: '3177459971'
canonical_url_root: https://staging.theline.com
mailassets_url_root: https://staging.theline.com
optimizely_enabled: false
optimizely_project_id: '1292961881'
webfonts_enabled: true
usersnap_api_key: <%= ENV['USERSNAP_API_KEY'] || 'b2c5f822-ff74-4f90-9922-ce30a05d1fd5' %>
chartbeat_enabled: <%= ENV['CHARTBEAT_ENABLED'] || false %>
steelhouse_enabled: false
effective_spend_analytics_display: false
